/* Generated By:JJTree: Do not edit this line. AstLiteralExpression.java */

package com.sun.el.parser;

import javax.el.ELException;

import com.sun.el.lang.EvaluationContext;

/**
 * @author Jacob Hookom [jacob@hookom.net]
 * @version $Change: 181177 $$DateTime: 2001/06/26 08:45:09 $$Author: ja120114 $
 */
public final class AstLiteralExpression extends SimpleNode {
    public AstLiteralExpression(int id) {
        super(id);
    }

    public Class getType(EvaluationContext ctx)
            throws ELException {
        return String.class;
    }

    public Object getValue(EvaluationContext ctx)
            throws ELException {
        return this.image;
    }
    
	public void setImage(String image) {
		this.image = replace(image, "\\$", "$");
		this.image = replace(this.image, "\\#", "#");
	}
	
	protected static final String replace(String in, String a, String b) {
		StringBuffer sb = new StringBuffer(in);
		int loc = sb.indexOf(a);
		while (loc != -1) {
			sb.delete(loc, loc + a.length());
			sb.insert(loc, b);
			loc = sb.indexOf(a, loc);
		}
		return sb.toString();
	}
}
