/* Generated By:JJTree: Do not edit this line. AstLessThanEqual.java */

package com.sun.el.parser;

import javax.el.ELException;

import com.sun.el.lang.EvaluationContext;

/**
 * @author Jacob Hookom [jacob@hookom.net]
 * @version $Change: 181177 $$DateTime: 2001/06/26 08:45:09 $$Author: kchung $
 */
public final class AstLessThanEqual extends BooleanNode {
    public AstLessThanEqual(int id) {
        super(id);
    }

    public Object getValue(EvaluationContext ctx)
            throws ELException {
        Object obj0 = this.children[0].getValue(ctx);
        Object obj1 = this.children[1].getValue(ctx);
        return (compare(obj0, obj1) <= 0) ? Boolean.TRUE : Boolean.FALSE;
    }
}
