/*
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * glassfish/bootstrap/legal/CDDLv1.0.txt or
 * https://glassfish.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * glassfish/bootstrap/legal/CDDLv1.0.txt.  If applicable,
 * add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your
 * own identifying information: Portions Copyright [yyyy]
 * [name of copyright owner]
 *
 * Copyright 2005 Sun Microsystems, Inc. All rights reserved.
 *//* Generated By:JJTree: Do not edit this line. /tomc/web.align/webtier-alignment/prototype/el-ri/src/com/sun/el/parser/ELParserTreeConstants.java */

package com.sun.el.parser;

public interface ELParserTreeConstants
{
  public int JJTCOMPOSITEEXPRESSION = 0;
  public int JJTLITERALEXPRESSION = 1;
  public int JJTDEFERREDEXPRESSION = 2;
  public int JJTDYNAMICEXPRESSION = 3;
  public int JJTVOID = 4;
  public int JJTCHOICE = 5;
  public int JJTOR = 6;
  public int JJTAND = 7;
  public int JJTEQUAL = 8;
  public int JJTNOTEQUAL = 9;
  public int JJTLESSTHAN = 10;
  public int JJTGREATERTHAN = 11;
  public int JJTLESSTHANEQUAL = 12;
  public int JJTGREATERTHANEQUAL = 13;
  public int JJTPLUS = 14;
  public int JJTMINUS = 15;
  public int JJTMULT = 16;
  public int JJTDIV = 17;
  public int JJTMOD = 18;
  public int JJTNEGATIVE = 19;
  public int JJTNOT = 20;
  public int JJTEMPTY = 21;
  public int JJTVALUE = 22;
  public int JJTDOTSUFFIX = 23;
  public int JJTBRACKETSUFFIX = 24;
  public int JJTIDENTIFIER = 25;
  public int JJTFUNCTION = 26;
  public int JJTTRUE = 27;
  public int JJTFALSE = 28;
  public int JJTFLOATINGPOINT = 29;
  public int JJTINTEGER = 30;
  public int JJTSTRING = 31;
  public int JJTNULL = 32;


  public String[] jjtNodeName = {
    "CompositeExpression",
    "LiteralExpression",
    "DeferredExpression",
    "DynamicExpression",
    "void",
    "Choice",
    "Or",
    "And",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessThanEqual",
    "GreaterThanEqual",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Mod",
    "Negative",
    "Not",
    "Empty",
    "Value",
    "DotSuffix",
    "BracketSuffix",
    "Identifier",
    "Function",
    "True",
    "False",
    "FloatingPoint",
    "Integer",
    "String",
    "Null",
  };
}
